-- MySQL Script generated by MySQL Workbench
-- Thu Jul 26 15:54:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `Email` NVARCHAR(45) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `ProjectID` INT NOT NULL,
  `ProjectName` VARCHAR(45) NOT NULL,
  `ToDo` ENUM('Yes', 'No') NULL,
  `Doing` ENUM('Yes', 'No') NULL,
  `Done` ENUM('Yes', 'No') NULL,
  `TaskID` INT NOT NULL,
  PRIMARY KEY (`ProjectID`, `TaskID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account_Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account_Project` (
  `ProjectID` INT NOT NULL,
  `Email` NVARCHAR(45) NOT NULL,
  `Master` ENUM('Yes', 'No') NOT NULL,
  PRIMARY KEY (`ProjectID`, `Email`),
  INDEX `Email_idx` (`Email` ASC),
  CONSTRAINT `ProjectID`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `mydb`.`Project` (`ProjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Email`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`Account` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `TaskId` INT NOT NULL,
  `Email` NVARCHAR(45) NOT NULL,
  `Deadline` DATETIME NOT NULL,
  `Describle` VARCHAR(100) NOT NULL,
  `TestStatus` ENUM('Đã Test', 'Đang test', 'Chưa Test') NOT NULL,
  PRIMARY KEY (`TaskId`, `Email`),
  INDEX `Email_idx` (`Email` ASC),
  CONSTRAINT `TaskId`
    FOREIGN KEY (`TaskId`)
    REFERENCES `mydb`.`Project` (`TaskID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Email`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`Account_Project` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
